spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

accounts:
  message: "Welcome to EazyBank related prod APIs "
  contactDetails:
    name: "Vijay Kumar - Project Lead"
    email: "vijay.k@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345

